<?php
$items = $block->getCartItems();
$count = 0;
foreach ($items as $item) {
    if ($block->getProductsData($item->getProductId())) {
        $count++;
    }
}
?>

<div id="customModal" style="display: none;">
    <div id="minicart-content-wrapper">
        <div class="content-wrapper">
            <?php if ($count > 0) : ?>
                <div>
                    <h3>Do you want to add the following products to your cart?</h3>
                    <br>
                    <div class="cartProductList" id="cartProductList" style="display: flex; justify-content:space-around; flex-wrap: wrap;">
                        <?php foreach ($items as $item) : ?>
                            <?php
                            if ($block->getProductsData($item->getProductId())) {
                                $suggestProductId = $block->getProductsData($item->getProductId());
                            } else  $suggestProductId = '';

                            if ($suggestProductId != '') {
                                $suggestProduct = $block->getProductById($suggestProductId);
                                $addToCartUrl =  $block->AddToCart($suggestProduct);
                                $image = $suggestProduct->getSmallImage() == '' ? '/pub/static/frontend/Clear/usb2u/en_GB/images/default-category-image_1.png' : '/pub/media/catalog/product' . $suggestProduct->getSmallImage();
                                $name = $suggestProduct->getName();
                                $price = $suggestProduct->getPrice();
                            ?>
                                <div class="product-box" style="display: flex; gap: 24px; flex-direction: column;">
                                    <!-- name - price -->
                                    <p style="max-width: 200px;"><strong class="ids"><?= $name ?></strong> - <span class="price">As low as $<?= $price ?></span> </p>

                                    <!-- img -->
                                    <img width="150px" height="150px" src="<?php echo $image; ?>">

                                    <!-- add product -->
                                    <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post" id="tocart-form">
                                        <?php echo $block->getBlockHtml('formkey') ?>
                                        <div class="btn">
                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                                                <span>Add to Cart</span>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            <?php } ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php else : ?>
                <div class="emptyList">There are no recommended products for these items</div>
            <?php endif; ?>


            <div>
                <button class="action go-to-checkout primary" style="margin-top:48px; float: right; width: 250px; line-height: 2.2rem; padding: 14px 17px; font-size: 1.8rem;">
                    Proceed to Checkout
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal) {
        $(document).ready(function() {
            $('.go-to-checkout').on("click", function(events) {
                window.location.href = '<?php echo $block->escapeUrl($block->getCheckoutUrl()) ?>';
            });
        });
    });
</script>