<?php
$items = $block->getCartItems();
?>

<div id="customModal" style="display: none;">
    <div id="minicart-content-wrapper">
        <?php if (count($items) > 0) : ?>
            <h3>Do you want to add the following products to your cart?</h3>
            <br>
            <div class="cartProductList" id="cartProductList" style="display: flex; justify-content:space-around; flex-wrap: wrap;">
                <?php foreach ($items as $item) : ?>
                    <?php
                    if ($block->getProductsData($item->getProductId())) {
                        $suggestProductId = $block->getProductsData($item->getProductId());
                    } else  $suggestProductId = '';
                    if ($suggestProductId != '') {
                        $suggestProduct = $block->getProductById($suggestProductId);
                        $addToCartUrl =  $block->AddToCart($suggestProduct);
                        $image = $suggestProduct->getSmallImage() == '' ? '/pub/static/frontend/Clear/usb2u/en_GB/images/default-category-image_1.png' : '/pub/media/catalog/product' . $suggestProduct->getSmallImage();
                    }
                    ?>

                    <div class="product-box" style="display: flex; gap: 24px; flex-direction: column;">
                        <p style="max-width: 200px;"><strong class="ids"><?php echo $suggestProduct->getName(); ?></strong> - <span class="price">As low as $<?php echo $suggestProduct->getPrice(); ?></span> </p>
                        <img width="150px" height="150px" src="<?php echo $image; ?>">

                        <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post" id="tocart-form">
                            <?php echo $block->getBlockHtml('formkey') ?>
                            <div class="btn">
                                <button type="submit" title="Add to Cart" class="action tocart primary">
                                    <span>Add to Cart</span>
                                </button>
                            </div>
                        </form>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php else : ?>
            <div class="emptyList">No products in your Cart.</div>
        <?php endif; ?>

        <br>
        <br>
        <div><button class="action go-to-checkout primary">Go to checkout</button></div>
    </div>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal) {
        $(document).ready(function() {
            $('.go-to-checkout').on("click", function(events) {
                window.location.href = '<?php echo $block->escapeUrl($block->getCheckoutUrl()) ?>';
            });
        });
    });
</script>