<div>
    <form class="bt-tab-form" action="<?php echo $block->getUrl('managetab/tab/save', ['_current' => true]); ?>" method="post">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey(); ?>">
        <input type="hidden" name="tab_id" value="<?php echo $block->getTabId(); ?>">
        <div>
            <label for="name"><?php echo __('Name'); ?></label>
            <input type="text" id="name" name="name" value="<?php echo $block->getTabName(); ?>" required>
        </div>
        <div>
            <label for="content"><?php echo __('Content'); ?></label>
            <textarea id="content" name="content" required><?php echo $block->getTabContent(); ?></textarea>
        </div>
        <div>
            <label for="status"><?php echo __('Status'); ?></label>
            <select id="status" name="status" required>
                <option value="1" <?php if ($block->getTabStatus() == 1) echo ' selected="selected"'; ?>><?php echo __('Enabled'); ?></option>
                <option value="0" <?php if ($block->getTabStatus() == 0) echo ' selected="selected"'; ?>><?php echo __('Disabled'); ?></option>
            </select>
        </div>
        <div>
            <button type="submit"><?php echo __('Save'); ?></button>
        </div>
    </form>
</div>

<style>
    .bt-tab-form {
        display: flex;
        flex-direction: column;
        gap: 32px;
    }
</style>