<div class="form-edit">
    <h3>EDIT Item table</h3>
    <form method="post" action="action?act=do_edit">
        <?php
        $id = isset($_GET["id"]) ? $_GET["id"] : "";
        foreach ($block->getCollectionById($id) as $key => $item) {
        ?>
            <input type="text" name="idedit" placeholder="id" value="<?php echo $item->getId(); ?>" />
            <input type="text" name="field1" placeholder="field1" value="<?php echo $item->getData('field1') ?>"/>
            <input type="text" name="field2" placeholder="field2" value="<?php echo $item->getData('field2') ?>"/>
        <?php } ?>
        <button type="submit">EDIT</button>
    </form>
</div>

<style>
    .form-edit {
        border: 1px solid gray;
        padding: 20px;
    }

    .form-edit form {
        display: flex;
        gap: 16px;
    }
</style>