<div class="search-section" data-enable=<?php echo $block->getEnableSidebarContent();  ?>>
    <h3>FAQ</h3>
    <input class="search-box" type="text" name="" id="" placeholder="Search FAQ">
    <div class="list">
        <ul>
            <?php
            $list = ["How do i find my order", "How does buyin work", "How many fees are there", "How do i sign out", "How do i message", "How do i refund items"];
            $maxLength = $block->getCustomQuantity();
            $count = 0;

            foreach ($list as $item) {
                $count++;
                if ($count > $maxLength) break;
            ?>
                <li><?php echo $item ?></li>
            <?php } ?>
        </ul>
    </div>
</div>

<style>
    .search-section {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        gap: 16px;
    }

    .search-box {
        max-width: 300px;
    }

    .list {
        width: 300px;
    }

    .list li {
        list-style-type: none;
    }
</style>