<div class="search-section" data-enable=<?php echo $block->getEnableSidebarContent();  ?>>
    <h3>FAQ</h3>
    <input class="search-box" type="text" name="" id="" placeholder="Search FAQ">
    <div class="list">
        <ul>
            <?php
            $list = ["How do i find my order", "How does buyin work", "How many fees are there", "How do i sign out", "How do i message", "How do i refund items"];
            $maxLength = $block->getCustomQuantity();
            $quantity = count($list);

            if ($maxLength < count($list)) {
                $quantity = $maxLength;
            } elseif ($maxLength < 0) $quantity = 0;

            for ($i = 0; $i < $quantity; $i++) {
            ?>
                <li><?php echo $list[$i] ?></li>
            <?php } ?>
        </ul>
    </div>
</div>

<style>
    .search-section {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        gap: 16px;
    }

    .search-box {
        max-width: 300px;
    }

    .list {
        width: 300px;
    }

    .list li {
        list-style-type: none;
    }
</style>