<div class="sidebar-content" data-enable=<?php echo $block->getEnableSidebarContent();  ?>>
    <h3>Help</h3>
    <p>you can contact us at: GreenTune@business.com</p>
    <p>you can call us at: 123-123-1234</p>
</div>

<style>
    .sidebar-content {
        margin-top: 100px;
    }

    .sidebar-content h3 {
        text-align: center;
    }
</style>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        const sidebarContent = $('.sidebar-content');
        const check = sidebarContent.attr('data-enable');
        if (check == 1) {
            sidebarContent.css("display", "block")
        } else {
            sidebarContent.css("display", "none")
        }

    });
</script>