<div class="title">
    <h2 class="title-content" data-enable=<?php echo $block->getEnableTitle();  ?>>
        <?php echo $block->getCustomTitle();  ?>
    </h2>
</div>

<style>
    h2 {
        color: goldenrod;
        text-align: center;
    }
</style>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        const title = $('.title-content');
        const check = title.attr('data-enable');
        if (check == 1) {
            title.css("display", "block")
        } else {
            title.css("display", "none")
        }

    });
</script>